//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int AccountingID { get; set; }
        public int CustomerID { get; set; }
        public int TypeID { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual AccoutingTypes AccoutingTypes { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
